extension/pages/popup/popup.html, extension/pages/popup/popup.js
- Added button to popup that takes user to API key page when no API key is set;
=> API qicklink

extension/changelog.js, extension/pages/settings/settings.html, extension/scripts/background.js, extension/scripts/content/global/ttGlobal.entry.css, extension/scripts/content/global/ttGlobal.entry.js, extension/scripts/global/globalData.js
https://github.com/Mephiles/torntools_2/issues/20
Gave it a shot, tried to follow the existing structure and conventions of the project, but if I missed something let me know and I'll change it.
=> #20 Refill Highlights

extension/pages/popup/dashboard.css, extension/pages/popup/popup.css
Fixed bar was going outside of popout window when above max value [Energy >150]
Fixed bar-title being to close to bars.
=> Fixed bars

extension/scripts/background.js
Simple PR to have the volume slider apply to TTS volume
=> Apply volume option to TTS

extension/manifest.json, extension/pages/settings/preferences.css, extension/pages/settings/settings.html, extension/pages/settings/settings.js, extension/scripts/features/hidecasinogames/ttHideCasinoGames.css, extension/scripts/features/hidecasinogames/ttHideCasinoGames.js, extension/scripts/global/functions/torn.js, extension/scripts/global/globalData.js
=> Hide Casino Games

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/content/global/ttGlobal.entry.js, extension/scripts/features/hidegymhighlight/ttHideGymHighlight.css, extension/scripts/features/hidegymhighlight/ttHideGymHighlight.js, extension/scripts/global/functions/torn.js, extension/scripts/global/globalData.js
=> Hide Gym Highlight

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/stockacronyms/ttStockAcronyms.css, extension/scripts/features/stockacronyms/ttStockAcronyms.js, extension/scripts/global/globalData.js
=> Stock Acronyms

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/autoapifill/ttAutoAPIFill.js, extension/scripts/global/globalData.js
=> API Key Auto Fill

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/profilenotes/ttProfileNotes.css, extension/scripts/features/profilenotes/ttProfileNotes.js, extension/scripts/global/globalData.js
=> Profile notes

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/totalitemcost/ttTotalItemCost.css, extension/scripts/features/totalitemcost/ttTotaltemCost.js, extension/scripts/global/globalData.js
=> Show total price when buying an item

extension/pages/popup/popup.html
=> Popup Travel Link Fix

extension/manifest.json, extension/scripts/features/autopretty/ttAutoPretty.js, extension/scripts/global/globalData.js
=> Auto pretty API Demo

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/apiselections/ttAPISelections.css, extension/scripts/features/apiselections/ttAPISelections.js, extension/scripts/global/globalData.js
=> Make API Selections clickable

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/tradeopenchat/ttTradeOpenChat.css, extension/scripts/features/tradeopenchat/ttTradeOpenChat.js, extension/scripts/features/tradevalues/ttTradeValues.css, extension/scripts/features/tradevalues/ttTradeValues.js, extension/scripts/global/globalData.js, extension/scripts/global/globalVariables.css
This PR contains:
1. Adding values of items in Trade. Closes #56 .
2. Button to open chat with the trader. No issue linked.
=> Trade features

extension/scripts/features/tradeopenchat/ttTradeOpenChat.js, extension/scripts/features/tradevalues/ttTradeValues.js
=> Fix trading feature not loading

extension/scripts/features/abroadpeoplefilter/ttPeopleFilter.js, extension/scripts/features/hospitalfilter/ttHospitalFilter.js, extension/scripts/features/jailfilter/ttJailFilter.js, extension/scripts/global/functions/formatting.js, extension/scripts/global/functions/slider.css, extension/scripts/global/functions/slider.js
=> Improve filter sliders.

extension/changelog.json, extension/scripts/features/searchchat/ttSearchChat.js
=> Filter Chats by user name

extension/pages/settings/preferences.css, extension/pages/settings/settings.css, extension/pages/settings/settings.html, extension/pages/settings/settings.js
=> Preferences search

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/bazaarfillmax/ttBazaarFillMax.css, extension/scripts/features/bazaarfillmax/ttBazaarFillMax.js, extension/scripts/features/shopsfillmax/ttShopsFillMax.css, extension/scripts/features/shopsfillmax/ttShopsFillMax.js, extension/scripts/global/globalData.js
=> Fill max for Bazaar & City Shops

extension/scripts/content/global/ttGlobal.js, extension/scripts/features/searchchat/ttSearchChat.js, extension/scripts/global/functions/listeners.js
=> Reconnect chat fix

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/greycompletedcourses/ttGreyCompletedCourses.css, extension/scripts/features/greycompletedcourses/ttGreyCompletedCourses.js, extension/scripts/global/globalData.js
=> Grey out completed Education Categories

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/bar-links/ttBarLinks.css, extension/scripts/features/bar-links/ttBarLinks.js, extension/scripts/global/globalData.js
=> Add bar links in the sidebar.

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/background.js, extension/scripts/features/api-marking/ttAPIMarking.css, extension/scripts/features/api-marking/ttAPIMarking.js, extension/scripts/global/globalData.js
=> Display API markings to show what data we use.

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/csv-war-report/ttCSVWarReport.css, extension/scripts/features/csv-war-report/ttCSVWarReport.js, extension/scripts/global/functions/containers.js, extension/scripts/global/globalData.js
=> War report to CSV

extension/scripts/features/settings-link/ttSettingsLink.css, extension/scripts/features/settings-link/ttSettingsLink.js
=> Properly center settings back button

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/property-values/ttPropertyValues.js, extension/scripts/global/globalData.js
=> Property Values

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/education-finish-time/ttEducationFinishTime.js, extension/scripts/global/globalData.js
=> Show Education Course Finish Time

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/csv-chain-report/ttCSVChainReport.css, extension/scripts/features/csv-chain-report/ttCSVChainReport.js, extension/scripts/features/csv-war-report/ttCSVWarReport.js, extension/scripts/global/globalData.js
=> Chain Report to CSV

extension/scripts/global/elements/table/ttTable.css
=> Bank Table "g" getting cut fix

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/content/gym/ttGym.js, extension/scripts/features/specialist-gyms/ttSpecialistGyms.css, extension/scripts/features/specialist-gyms/ttSpecialistGyms.js, extension/scripts/global/functions/containers.js, extension/scripts/global/functions/listeners.js, extension/scripts/global/functions/torn.js, extension/scripts/global/functions/utilities.js, extension/scripts/global/globalData.js, extension/scripts/global/globalStyle.css
=> Show speciality gym requirements.

extension/scripts/features/highlight-own-oc/ttHighlightOwnOC.js, extension/scripts/features/oc-available-players/ttOCAvailablePlayers.js, extension/scripts/features/open-oc/ttOpenOC.js, extension/scripts/features/scrape-oc/ttScrapeOC.js
Add a start function and remove them properly.
=> Apply several fixes for oc features.

extension/pages/settings/about.css, extension/pages/settings/preferences.css, extension/pages/settings/settings.css, extension/pages/settings/settings.html, extension/pages/settings/settings.js, extension/scripts/global/globalData.js, extension/scripts/global/team.js
=> Provide updated to the about page.

extension/pages/popup/calculator.css, extension/pages/popup/market.css, extension/pages/popup/popup.css, extension/pages/popup/popup.html, extension/pages/popup/popup.js, extension/pages/popup/stocks.css, extension/scripts/global/globalData.js
=> Add the calculator to the popup.

extension/manifest.json, extension/scripts/content/crimes/ttCrimes.js, extension/scripts/features/quick-crimes/ttQuickCrimes.css, extension/scripts/features/quick-crimes/ttQuickCrimes.js, extension/scripts/global/functions/api.js, extension/scripts/global/functions/containers.js, extension/scripts/global/functions/dom.js, extension/scripts/global/functions/listeners.js, extension/scripts/global/globalData.js, extension/scripts/global/inject/xhr.inject.js
=> Add the quick crime functionality.

extension/manifest.json, extension/scripts/content/missions/ttMissions.js, extension/scripts/features/mission-hints/ttMissionHints.css, extension/scripts/features/mission-hints/ttMissionHints.js, extension/scripts/global/functions/listeners.js, extension/scripts/global/globalData.js
=> Show mission hints.

extension/scripts/features/quick-items/ttQuickItems.js
=> Quick item fixes

extension/manifest.json, extension/pages/settings/settings.html, extension/pages/settings/settings.js, extension/scripts/content/trade/ttTrade.js, extension/scripts/features/no-confirm/ttItemMarketNoConfirm.js, extension/scripts/features/no-confirm/ttItemNoConfirm.js, extension/scripts/features/no-confirm/ttTradeNoConfirm.js, extension/scripts/features/trade-open-chat/ttTradeOpenChat.js, extension/scripts/features/trade-values/ttTradeValues.js, extension/scripts/global/functions/listeners.js, extension/scripts/global/globalData.js, extension/scripts/global/inject/xhr.inject.js
=> Remove several confirmation messages.

extension/changelog.json, extension/pages/settings/settings.html, extension/pages/settings/settings.js, extension/scripts/global/functions/formatting.js, extension/scripts/global/globalData.js
=> Show dates and time in TCT instead of local time.

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/total-portfolio-value/ttTotalPortfolioValue.css, extension/scripts/features/total-portfolio-value/ttTotalPortfolioValue.js, extension/scripts/global/globalData.js
=> Total stock value

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/landing-time/ttLandingTime.css, extension/scripts/features/landing-time/ttLandingTime.js, extension/scripts/global/globalData.js
=> Show the landing time when flying.

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/csv-challenge-contributions/ttCSVChallengeContributions.css, extension/scripts/features/csv-challenge-contributions/ttCSVChallengeContributions.js, extension/scripts/global/globalData.js
=> Challenge contribs csv

extension/pages/settings/settings.html, extension/scripts/features/city-items/ttCityItems.css, extension/scripts/features/city-items/ttCityItems.js, extension/scripts/global/globalData.js
- Improve design.
- Combine duplicate items.
=> Make adjustments to the city items.

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/content/travelagency/ttTravelAgency.js, extension/scripts/features/flying-time/ttFlyingTime.css, extension/scripts/features/flying-time/ttFlyingTime.js, extension/scripts/global/functions/formatting.js, extension/scripts/global/functions/listeners.js, extension/scripts/global/globalData.js
=> Show time when you'd land back in Torn.

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/background.js, extension/scripts/features/mission-rewards/ttMissionRewards.css, extension/scripts/features/mission-rewards/ttMissionRewards.js, extension/scripts/global/globalData.js
=> Show mission reward information.

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/abroad-items-filter/ttAbroadItemsFilter.css, extension/scripts/features/abroad-items-filter/ttAbroadItemsFilter.js, extension/scripts/features/abroad-people-filter/ttPeopleFilter.js, extension/scripts/global/globalData.js
=> Abroad item filter

extension/manifest.json, extension/scripts/features/abroad-items-filter/ttAbroadItemsFilter.js, extension/scripts/features/abroad-people-filter/ttPeopleFilter.js, extension/scripts/global/elements/checkbox-list/ttCheckboxList.js, extension/scripts/global/elements/checkbox/ttCheckbox.js, extension/scripts/global/functions/containers.js, extension/scripts/global/functions/filters.css, extension/scripts/global/functions/filters.js, extension/scripts/global/functions/torn.js, extension/scripts/global/globalData.js
=> New abroad people filter && New tools for filters

extension/pages/settings/export.css, extension/pages/settings/settings.css, extension/pages/settings/settings.html, extension/pages/settings/settings.js, extension/scripts/features/profile-id/ttProfileID.js, extension/scripts/global/functions/pages.js, extension/scripts/global/functions/utilities.js
=> Local export.

extension/pages/settings/export.css, extension/pages/settings/settings.html, extension/pages/settings/settings.js, extension/scripts/global/functions/pages.css
=> Remote export.

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/content/userlist/ttUserlist.js, extension/scripts/features/userlist-filter/ttUserlistFilter.js, extension/scripts/global/functions/filters.js, extension/scripts/global/functions/listeners.js, extension/scripts/global/functions/torn.js, extension/scripts/global/globalData.js
=> Userlist filter

extension/pages/settings/settings.js
- Go to the right section based on the url.
- Scroll to top when switching sections.
=> Some changes to the preferences page.

extension/scripts/content/missions/ttMissions.js
Should solve mission hints not loading after switching agents or accept missions.
Awaiting some more testing before merging.
=> Solve mission not loading.

extension/manifest.json, extension/pages/settings/settings.html, extension/resources/images/svg-icons/cross.svg, extension/scripts/features/disable-ally-attacks/ttDisableAllyAttacks.css, extension/scripts/features/disable-ally-attacks/ttDisableAllyAttacks.js, extension/scripts/global/globalData.js
=> Disable Ally Attacks

extension/scripts/global/featureManager.js, extension/scripts/global/globalStyle.css
=> Feature Manager Only Failed Features Not Working Fix

extension/manifest.json, extension/scripts/content/travelagency/ttTravelAgency.js, extension/scripts/features/achievements/ttAchievements.js, extension/scripts/features/bank-investment-info/ttBankInvestmentInfo.css, extension/scripts/features/bank-investment-info/ttBankInvestmentInfo.js, extension/scripts/features/bounty-filter/ttBountyFilter.js, extension/scripts/features/casino-net-total/ttCasinoNetTotal.css, extension/scripts/features/casino-net-total/ttCasinoNetTotal.js, extension/scripts/features/custom-links/ttCustomLinks.css, extension/scripts/features/disable-ally-attacks/ttDisableAllyAttacks.css, extension/scripts/features/disable-ally-attacks/ttDisableAllyAttacksLoader.js, extension/scripts/features/flying-time/ttFlyingTime.js, extension/scripts/features/fold-faction-infobox/ttFoldFactionInfobox.css, extension/scripts/features/forum-warning/ttForumWarning.css, extension/scripts/features/forum-warning/ttForumWarning.js, extension/scripts/features/item-values/ttItemValues.css, extension/scripts/features/item-values/ttItemValues.js, extension/scripts/features/jail-filter/ttJailFilter.css, extension/scripts/features/settings-link/ttSettingsLink.js, extension/scripts/features/total-portfolio-value/ttTotalPortfolioValue.css, extension/scripts/features/total-portfolio-value/ttTotalPortfolioValue.js, extension/scripts/global/functions/containers.css, extension/scripts/global/globalStyle.css
=> Tablet mode fixes

extension/scripts/features/job-specials/ttJobSpecials.js
=> Company Specials Fix

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/racing-upgrades/ttRacingUpgrades.css, extension/scripts/features/racing-upgrades/ttRacingUpgrades.js, extension/scripts/global/globalData.js
=> Show racing upgrade values.

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/background.js, extension/scripts/features/attack-timeout-warning/ttAttackTimeoutWarning.js, extension/scripts/global/functions/formatting.js, extension/scripts/global/globalData.js
=> Warn when an attack is about to timeout.

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/shop-profits/ttShopProfits.css, extension/scripts/features/shop-profits/ttShopProfits.js, extension/scripts/global/globalData.js
=> Show shop profits.

extension/scripts/background.js, extension/scripts/global/functions/browser.js, extension/scripts/service-worker.js
Solves notification on Kiwi not working.
=> Send notifications through a service worker if the normal way doesn't work.

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/content/factions/ttFactions.js, extension/scripts/features/armory-filter/ttArmoryFilter.js, extension/scripts/features/faction-member-filter/ttFactionMemberFilter.js, extension/scripts/global/globalData.js
=> Armory filter

extension/scripts/features/car-win-percentage/ttCarWinPercentage.js
=> Fix NaN Racing Issue

extension/pages/settings/settings.html
=> Improve `settings.html` browser sync description

extension/scripts/features/drug-details/ttDrugDetails.js
=> Drug Details Fix

extension/pages/settings/settings.js, extension/scripts/features/employee-inactivity-warning/ttEmployeeInactivityWarning.js, extension/scripts/global/featureManager.js, extension/scripts/global/globalData.js
=> Employee Inactivity Fix

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/content/factions/ttFactions.js, extension/scripts/features/csv-challenge-contributions/ttCSVChallengeContributions.js, extension/scripts/features/upgrade-req-respect/ttUpgrdReqRespect.js, extension/scripts/features/upgrade-required-respect/ttUpgradeRequiredRespect.js, extension/scripts/global/functions/listeners.js, extension/scripts/global/globalData.js
=> Show required respect

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/armory-worth/ttArmoryWorth.css, extension/scripts/features/armory-worth/ttArmoryWorth.js, extension/scripts/global/globalData.js
=> Armory Worth

extension/manifest.json, extension/pages/settings/settings.html, extension/pages/settings/settings.js, extension/scripts/features/faction-inactivity-warning/ttFactionInactivityWarning.css, extension/scripts/features/faction-inactivity-warning/ttFactionInactivityWarning.js, extension/scripts/global/globalData.js
=> Faction Member Inactivity Warning

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/profile-box/ttProfileBox.js, extension/scripts/features/stats-estimate/statsEstimate.js, extension/scripts/features/stats-estimate/ttStatsEstimate.css, extension/scripts/features/stats-estimate/ttStatsEstimateProfile.js, extension/scripts/global/functions/listeners.js, extension/scripts/global/globalData.js
=> Implement profile stat estimates.

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/stats-estimate/statsEstimate.js, extension/scripts/features/stats-estimate/ttStatsEstimate.css, extension/scripts/features/stats-estimate/ttStatsEstimateAttacks.js, extension/scripts/features/stats-estimate/ttStatsEstimateEnemies.js, extension/scripts/features/stats-estimate/ttStatsEstimateHOF.js, extension/scripts/features/stats-estimate/ttStatsEstimateProfile.js, extension/scripts/features/stats-estimate/ttStatsEstimateUserlist.js, extension/scripts/features/userlist-filter/ttUserlistFilter.js, extension/scripts/global/functions/listeners.js, extension/scripts/global/globalData.js
Implement stats estimates for
- enemies
- hof
- attacks page
- userlist (+ filter)
#66
=> Further stats estimates implementation.

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/content/bounties/ttBounties.js, extension/scripts/features/bounty-filter/ttBountyFilter.js, extension/scripts/features/faction-member-filter/ttFactionMemberFilter.js, extension/scripts/features/stats-estimate/statsEstimate.js, extension/scripts/features/stats-estimate/ttStatsEstimate.css, extension/scripts/features/stats-estimate/ttStatsEstimateBounties.js, extension/scripts/features/stats-estimate/ttStatsEstimateFactionMembers.js, extension/scripts/features/stats-estimate/ttStatsEstimateUserlist.js, extension/scripts/global/functions/dom.js, extension/scripts/global/functions/filters.js, extension/scripts/global/functions/listeners.js, extension/scripts/global/globalData.js
Implement stats estimates for bounties and faction members.
#66
=> More stats estimates

extension/scripts/features/faction-member-filter/ttFactionMemberFilter.js, extension/scripts/global/globalData.js
=> Always set last action filter to the max if that was the case previously.

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/abroad-people-filter/ttPeopleFilter.js, extension/scripts/features/stats-estimate/statsEstimate.js, extension/scripts/features/stats-estimate/ttStatsEstimate.css, extension/scripts/features/stats-estimate/ttStatsEstimateAbroad.js, extension/scripts/features/stats-estimate/ttStatsEstimateFactionWars.js, extension/scripts/global/functions/filters.css, extension/scripts/global/globalData.js
=> Abroad and war stats estimate

extension/manifest.json, extension/scripts/features/creators/ttCreators.css, extension/scripts/features/creators/ttCreators.js, extension/scripts/features/profile-id/ttProfileID.js, extension/scripts/global/team.js
=> Show creator indicator.

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/high-low-helper/ttHighLowHelper.css, extension/scripts/features/high-low-helper/ttHighLowHelper.js, extension/scripts/global/globalData.js
=> Implement high low helper.

extension/manifest.json, extension/scripts/features/forum-menu/ttForumMenu.css, extension/scripts/features/forum-menu/ttForumMenu.js, extension/scripts/global/globalData.js
=> Add the menu to the forums.

extension/changelog.json, extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/hide-chat/ttHideChat.css, extension/scripts/features/hide-chat/ttHideChat.js, extension/scripts/global/globalData.js
=> Implement the option to hide chats.

extension/manifest.json, extension/scripts/features/travel-cooldowns/ttTravelCooldowns.css, extension/scripts/features/travel-cooldowns/ttTravelCooldowns.js, extension/scripts/global/globalData.js
=> Implement cooldown warnings before flying.

extension/pages/settings/preferences.css, extension/pages/targets/stakeouts.css, extension/pages/targets/targets.js, extension/scripts/background.js, extension/scripts/features/profile-box/ttProfileBox.js, extension/scripts/global/functions/pages.css
Also improves all stakeout notifications.
Closes #385
=> Allow stakeouts for offline hours.

extension/manifest.json, extension/pages/settings/settings.html, extension/pages/settings/settings.js, extension/scripts/features/revive-request/ttReviveRequest.css, extension/scripts/features/revive-request/ttReviveRequest.js, extension/scripts/global/functions/api.js, extension/scripts/global/functions/torn.js, extension/scripts/global/globalData.js
=> Add the revive request button.

extension/changelog.json, extension/manifest.json, extension/scripts/features/weapon-experience/ttWeaponExperience.css, extension/scripts/features/weapon-experience/ttWeaponExperience.js, extension/scripts/global/globalData.js
=> Show weapon experience during an attack.

extension/manifest.json, extension/pages/settings/settings.html, extension/pages/settings/settings.js, extension/scripts/features/csv-chain-report/ttCSVChainReport.js, extension/scripts/features/csv-challenge-contributions/ttCSVChallengeContributions.js, extension/scripts/features/csv-war-report/ttCSVWarReport.js, extension/scripts/global/functions/csv.js, extension/scripts/global/functions/pages.css, extension/scripts/global/globalData.js
=> Allow the user to choose their CSV delimiter.

extension/manifest.json, extension/pages/settings/settings.html, extension/pages/settings/settings.js, extension/scripts/background.js, extension/scripts/features/highlight-cheap-items/ttHighlightCheapItems.css, extension/scripts/features/highlight-cheap-items/ttHighlightCheapItems.js, extension/scripts/global/globalData.js
=> Highlight cheap items on the market.

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/content/competition/ttCompetition.js, extension/scripts/features/competition-filter/ttCompetitionFilter.js, extension/scripts/global/globalData.js
=> Implement level competition filter.

extension/pages/settings/settings.js
=> Request permissions if they are missing.

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/features/hide-tutorials/ttHideTutorials.css, extension/scripts/features/hide-tutorials/ttHideTutorials.entry.js, extension/scripts/global/globalData.js
=> Hide tutorials.

extension/manifest.json, extension/pages/settings/settings.html, extension/pages/settings/settings.js, extension/scripts/features/user-alias/ttUserAlias.css, extension/scripts/features/user-alias/ttUserAlias.js, extension/scripts/features/user-alias/ttUserAliasProfile.js, extension/scripts/features/user-alias/ttUserAliasUserlist.js, extension/scripts/global/globalData.js
=> User Alias

.github/workflows/run-prettier.yml
Change the author of the formatting to be github_actions.
=> Update Prettier workflow.

extension/manifest.json, extension/pages/settings/settings.html, extension/scripts/content/global/ttGlobal.js, extension/scripts/features/shop-filters/ttShopFilters.css, extension/scripts/features/shop-filters/ttShopFilters.js, extension/scripts/global/functions/containers.css, extension/scripts/global/functions/containers.js, extension/scripts/global/functions/formatting.js, extension/scripts/global/globalData.js
=> Shop Filters
